name: Deploy Test Infra Local

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        required: true
        type: string
        default: eu-west-1
      TF_WORKING_DIRECTORY:
        required: true
        type: string
        default: terraform/test
      ENVIRONMENT:
        required: true
        type: string
        default: test
      DEPLOYMENT_ROLE:
        required: true
        type: string
        default: arn:aws:iam::486282667:role/terraform-test-10-11-25
      DEPLOYMENT_SESSION_NAME:
        required: true
        type: string
        default: github-actions-test-terraform-deployment
      RUNNER:
        required: false
        type: string
        default: ubuntu-latest
      TERRAFORM_VERSION:
        required: true
        type: string
        default: 1.3.9
      TIMEOUT_MINUTES:
        required: false
        type: number
        default: 60
      APP_ID:
        required: true
        type: string
      COMMENT:
        required: false
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
  packages: write
  pull-requests: write

jobs:
  plan:
    name: ${{ github.event.inputs.ENVIRONMENT || 'test' }} Terraform Plan
    runs-on: ${{ github.event.inputs.RUNNER || 'ubuntu-latest' }}
    permissions:
      id-token: write
      pull-requests: write
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Confirming Checked Out Branch
        run: echo "The checked out branch is ${{ github.ref_name }}"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.event.inputs.DEPLOYMENT_ROLE }}
          role-session-name: ${{ github.event.inputs.DEPLOYMENT_SESSION_NAME }}
          aws-region: ${{ github.event.inputs.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs.TERRAFORM_VERSION }}

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ github.event.inputs.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: communitiesuk

      - name: Replace GIT Config Global Url
        run: |
          echo "Setting Git config to use token"
          git config --global url."https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/communitiesuk".insteadOf "https://github.com/communitiesuk"

      - name: Terraform fmt
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: init
        run: terraform init -no-color

      - name: Terraform validate
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform show
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: show
        run: terraform show -no-color tfplan

      - name: Comment Plan on PR
        if: ${{ github.event_name == 'pull_request' && github.event.inputs.COMMENT == 'true' }}
        uses: actions/github-script@v7
        env:
          PLAN: "terraform\n${{ steps.show.outputs.stdout }}"
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\hcl
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\hcl
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.event.inputs.TF_WORKING_DIRECTORY }}\`, Workflow: \`${{ github.workflow }}\`*`;

            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }

  apply:
    name: ${{ github.event.inputs.ENVIRONMENT || 'test' }} Terraform Apply
    runs-on: ${{ github.event.inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ github.event.inputs.ENVIRONMENT || 'test' }}
    needs: plan
    timeout-minutes: ${{ github.event.inputs.TIMEOUT_MINUTES || 60 }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.event.inputs.DEPLOYMENT_ROLE }}
          role-session-name: ${{ github.event.inputs.DEPLOYMENT_SESSION_NAME }}
          aws-region: ${{ github.event.inputs.AWS_REGION }}

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs.TERRAFORM_VERSION }}

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ github.event.inputs.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: communitiesuk

      - name: Replace GIT Config Global Url
        run: |
          echo "Setting Git config to use token"
          git config --global url."https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/communitiesuk".insteadOf "https://github.com/communitiesuk"

      - name: Terraform init
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: init
        run: terraform init -no-color

      - name: Terraform plan
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform apply
        working-directory: ${{ github.event.inputs.TF_WORKING_DIRECTORY }}
        id: apply
        run: terraform apply -auto-approve 
