name: "Validate and plan for pull request"

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf_fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive
  validate_test:
    name: Validate test Terraform config
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/test
    secrets:
      access_key: "${{secrets.access_key_dev}}"
      secret_key: "${{secrets.secret_key_dev}}"
  validate_staging:
    name: Validate staging Terraform config
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/staging
    secrets:
      access_key: "${{secrets.access_key_dev}}"
      secret_key: "${{secrets.secret_key_dev}}"
  validate_production:
    name: Validate production Terraform config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1
      - name: Terraform Init
        run: terraform init -input=false -backend=false
        working-directory: terraform/production
      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/production
