name: "Reusable Terraform workflow"

on:
  workflow_call:
    inputs:
      workdir:
        required: false
        type: string
        default: '.'
        description: directory to run Terraform commands from
      apply:
        required: false
        type: boolean
        default: false
        description: whether to apply config, or otherwise just plan
      environment:
        required: false
        type: string
        description: If applying, specify a release "environment"
    secrets:
      access_key:
        required: true
      secret_Key:
        required: true

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.plan.outputs.stdout }}
      plan_exitcode: ${{ steps.plan.outputs.exitcode }}
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check formatting of all Terraform files
        id: fmt
        run: terraform fmt -check -diff -recursive
        working-directory: ./

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        # Terraform's "detailed-exitcode" codes are: 0 for "no changes", 1 for errors, 2 for "valid changes" 
        run: terraform plan -no-color -input=false -detailed-exitcode
        continue-on-error: true

      - name: Fail job if plan resulted in an error
        if: steps.plan.outputs.exitcode == 1
        run: exit 1

  apply:
    name: Terraform apply
    needs: plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: inputs.apply && needs.plan.outputs.plan_exitcode == 2
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: repeat_plan
        run: terraform plan -no-color -input=false -detailed-exitcode
        continue-on-error: true

      - name: Compare plans
        if: steps.repeat_plan.outputs.stdout != needs.plan.outputs.plan
        run: >
          echo "Plans have changed; restart the planning job and review it again";
          diff <(echo "${{steps.repeat_plan.outputs.stdout}}") <(echo "${{needs.plan.outputs.plan}}")

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
